### ISSUE TITLE
Crashing on nodebb 1.4.5 with node 4.4.4/6.10.1

### ISSUE THREAD

**Issue by rez0n** [exo-do/nodebb-plugin-exodo-tweaks#1]
`error:  Error: spawn ./watchdog.bash ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

**Comment by king-cat** [comment]
I am also having this same issue with nodebb 1.5.3
